import 'package:get/get.dart';

class Lang extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'no_subject': "No Subject",
          'language': 'Language',
          'english': 'English',
          'arabic': 'Arabic',
          'are_you_u_wtd': 'Are you sure to delete?',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'mark_as_read': 'Mark as read',
          'readreceipt': 'Read receipts',
          'security': 'Security',
          'swipe_gestures': 'Swipe Gestures',
          'signature': 'Signature',
          'logout': 'Logout',
          'off': 'Off',
          'on': 'On',
          'set_your_swipe_preferences': 'Set your swipe preferences',
          'set_your_sig': 'Set your signature',
          'starred': 'Starred',
          'search': 'Search',
          'login': 'Login',
          'email': 'Email',
          'inbox': 'Inbox',
          'drafts': 'Drafts',
          'sent': 'Sent',
          'spam': 'Spam',
          'junk': 'Junk',
          'reset_password': 'Reset Password',
          'attach_file': 'Attach File',
          'from_files': 'From File',
          'from_gallery': 'From Gallery',
          'more_options': 'More Options',
          'save_as_draft': 'Save as Draft',
          'request_read_receipt': 'Request Read Receipt',
          'convert_to_plain_text': 'Convert to plain text',
          'from': 'From',
          'to': 'To',
          'cc': 'CC',
          'edit': 'Edit',
          'bcc': 'Bcc',
          'subject': 'Subject',
          'send': 'Send',
          'reply': 'Reply',
          'resend': 'Resend',
          'forward': 'Forward',
          'new_message': 'New Message',
          'account_name': 'Account Name',
          'trash': 'Trash',
          'compose': 'Compose',
          'settings': 'Settings',
          'accounts': 'Accounts',
          'undo': 'Undo',
          'error': 'Error',
          'contact_us': 'Contact Us',
          'terms_and_condition': 'Terms and Condition',
          'valid_required': 'This field is required',
          'valid_email': 'Please enter a valid email',
          'valid_password': 'Please enter a valid password',
          'valid_name': 'Please enter a valid name',
          'valid_phone': 'Please enter a valid phone number',
          'valid_code': 'Please enter a valid code',
          'valid_subject': 'Please enter a valid subject',
          'valid_message': 'Please enter a valid message',
          'add_a_recipient': 'Please add a recipient',
          'msg_draft_saved': 'Draft saved successfully',
          'msg_email_deleted': 'Email deleted successfully',
          'msg_draft_deleted': 'Draft deleted successfully',
          'msg_email_sent': 'Email sent successfully',
          'confirm_save_draft':
              'You have made changes.\nWould you like to save them?',
          'mark_as_junk': 'Mark as junk',
          'mark_as_unread': 'Mark as unread',
          'archive': 'Archive',
          'toggle_flag': 'Toggle Flag',
          'move_to': 'Move to',
          'move_to_inbox': 'Move to inbox',
          'move_to_sent': 'Move to sent',
          'move_to_spam': 'Move to spam',
          'move_to_trash': 'Move to trash',
          'move_to_draft': 'Move to draft',
          'move_to_starred': 'Move to starred',
          'move_to_archive': 'Move to archive',
          'move_to_junk': 'Move to junk',
          'move_to_flagged': 'Move to flagged',
          'move_to_unread': 'Move to unread',
          'move_to_read': 'Move to read',
          'msg_email_archived': 'Email archived successfully',
          'msg_email_moved': 'Email moved successfully',
          'msg_email_unarchived': 'Email unarchived successfully',
          'msg_email_flagged': 'Email flagged successfully',
          'msg_email_unflagged': 'Email unflagged successfully',
          'msg_email_marked_as_junk': 'Email marked as junk successfully',
          'msg_email_marked_as_unread': 'Email marked as unread successfully',
          'msg_email_marked_as_read': 'Email marked as read successfully',
          'msg_email_starred': 'Email starred successfully',
          'msg_email_unstarred': 'Email unstarred successfully',
          'msg_email_deleted_from': 'Email deleted from',
          'msg_email_moved_to': 'Email moved to',
          'try_again': 'Try Again',
          'move_message': 'Move Message',
          'enter_search_text': 'Please enter a search term to continue',
          'msg_no_internet': 'No internet connection',
          'resend_otp': 'Resend OTP',
        },
        'ar': {
          'no_subject': "لا يوجد موضوع",
          'language': 'اللغة',
          'english': 'الإنجليزية',
          'arabic': 'العربية',
          'are_you_u_wtd': 'هل أنت متأكد أنك تريد الحذف؟',
          'delete': 'حذف',
          'cancel': 'إلغاء الأمر',
          'mark_as_read': 'تمييز كمقروء',
          'readreceipt': 'إيصالات قراءة',
          'security': 'الأمان',
          'swipe_gestures': 'إيماءات السحب',
          'signature': 'التوقيع',
          'logout': 'تسجيل الخروج',
          'off': 'معطل',
          'on': 'مفعل',
          'set_your_swipe_preferences': 'اضبط تفضيلات السحب لديك',
          'set_your_sig': 'اضبط توقيعك الخاص',
          'starred': 'معلم بنجمة',
          'search': 'البحث',
          'login': 'تسجيل دخول',
          'email': 'البريد الإلكتروني',
          'inbox': 'صندوق الوارد',
          'drafts': 'المسودات',
          'sent': 'الصادر',
          'spam': 'البريد العشوائي',
          'junk': 'الغيز مرغوب فيه',
          'reset_password': 'إعادة تعيين كلمة المرور',
          'attach_file': 'إرفاق ملف',
          'from_files': 'من الملفات',
          'from_gallery': 'من الاستوديو',
          'more_options': 'خيارات أكثر',
          'save_as_draft': 'حفظ كمسودة',
          'request_read_receipt': 'طلب إيصال القراءة',
          'convert_to_plain_text': 'تحويل إلى نص بسيط',
          'from': 'من',
          'to': 'إلى',
          'cc': 'نسخة إلى',
          'edit': 'تحرير',
          'bcc': 'نسخة مخفية إلى',
          'subject': 'الموضوع',
          'send': 'إرسال',
          'reply': 'رد',
          'resend': 'إعادة إرسال',
          'forward': 'إعادة توجيه',
          'new_message': 'رسالة جديدة',
          'account_name': 'اسم الحساب',
          'trash': 'المهملات',
          'compose': 'إنشاء',
          'settings': 'الإعدادات',
          'accounts': 'الحسابات',
          'undo': 'تراجع',
          'error': 'خطأ',
          'contact_us': 'تواصل معنا',
          'terms_and_condition': 'الشروط والأحكام',
          'valid_required': 'هذا الحقل مطلوب',
          'valid_email': 'يرجى إدخال بريد إلكتروني صحيح',
          'valid_password': 'يرجى إدخال كلمة مرور صحيحة',
          'valid_name': 'يرجى إدخال اسم صحيح',
          'valid_phone': 'يرجى إدخال رقم هاتف صحيح',
          'valid_code': 'يرجى إدخال رمز صحيح',
          'valid_subject': 'يرجى إدخال موضوع صحيح',
          'valid_message': 'يرجى إدخال رسالة صحيحة',
          'msg_draft_saved': 'تم حفظ المسودة بنجاح',
          'msg_email_deleted': 'تم حذف البريد الإلكتروني بنجاح',
          'msg_draft_deleted': 'تم حذف المسودة بنجاح',
          'msg_email_sent': 'تم إرسال البريد الإلكتروني بنجاح',
          'confirm_save_draft': 'لقد قمت بإجراء تغييرات.\nهل ترغب في حفظها؟',
          'mark_as_junk': 'تمييز كبريد غير هام',
          'mark_as_unread': 'تمييز كغير مقروء',
          'archive': 'أرشفة',
          'toggle_flag': 'تغيير تمييز',
          'move_to': 'نقل إلى',
          'move_to_inbox': 'نقل إلى صندوق الوارد',
          'move_to_sent': 'نقل إلى الصادر',
          'move_to_spam': 'نقل إلى البريد العشوائي',
          'move_to_trash': 'نقل إلى المهملات',
          'move_to_draft': 'نقل إلى المسودات',
          'move_to_starred': 'نقل إلى المعلم بنجمة',
          'move_to_archive': 'نقل إلى الأرشيف',
          'move_to_junk': 'نقل إلى الغيز مرغوب فيه',
          'move_to_flagged': 'نقل إلى المعلم',
          'move_to_unread': 'نقل إلى غير مقروء',
          'move_to_read': 'نقل إلى مقروء',
          'msg_email_archived': 'تم أرشفة البريد الإلكتروني بنجاح',
          'msg_email_moved': 'تم نقل البريد الإلكتروني بنجاح',
          'msg_email_unarchived': 'تم إلغاء أرشفة البريد الإلكتروني بنجاح',
          'msg_email_flagged': 'تم تمييز البريد الإلكتروني بنجاح',
          'msg_email_unflagged': 'تم إلغاء تمييز البريد الإلكتروني بنجاح',
          'msg_email_marked_as_junk':
              'تم تمييز البريد الإلكتروني كغير هام بنجاح',
          'msg_email_marked_as_unread':
              'تم تمييز البريد الإلكتروني كغير مقروء بنجاح',
          'msg_email_marked_as_read': 'تم تمييز البريد الإلكتروني كمقروء بنجاح',
          'msg_email_starred': 'تم تمييز البريد الإلكتروني بنجاح',
          'msg_email_unstarred': 'تم إلغاء تمييز البريد الإلكتروني بنجاح',
          'msg_email_deleted_from': 'تم حذف البريد الإلكتروني من',
          'msg_email_moved_to': 'تم نقل البريد الإلكتروني إلى',
          'try_again': 'حاول مرة أخرى',
          'move_message': 'Move Message',
          'enter_search_text': 'يرجى إدخال مصطلح بحث للمتابعة',
          'msg_no_internet': 'لا يوجد اتصال بالإنترنت',
          'resend_otp': 'إعادة إرسال رمز التحقق',
        }
      };
}
