import 'package:get/get.dart';

class Lang extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'no_subject': "No Subject",
          'language': 'Language',
          'english': 'English',
          'arabic': 'Arabic',
          'are_you_u_wtd': 'Are you sure to delete?',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'mark_as_read': 'Mark as read',
          'readreceipt': 'Read receipts',
          'security': 'Security',
          'swipe_gestures': 'Swipe Gestures',
          'signature': 'Signature',
          'logout': 'Logout',
          'off': 'Off',
          'on': 'On',
          'set_your_swipe_preferences': 'Set your swipe preferences',
          'set_your_sig': 'Set your signature',
          'starred': 'Starred',
          'search': 'Search',
          'login': 'Login',
          'email': 'Email',
          'inbox': 'Inbox',
          'reset_password': 'Reset Password',
          'attach_file': 'Attach File',
          'from_files': 'From File',
          'from_gallery': 'From File',
          'more_options': 'More Options',
          'save_as_draft': 'Save as Draft',
          'request_read_receipt': 'Request Read Receipt',
          'convert_to_plain_text': 'Convert to plain text',
          'from': 'From',
          'to': 'To',
          'cc': 'CC',
          'edit': 'Edit',
          'bcc': 'Bcc',
          'subject': 'Subject',
          'send': 'Send',
          'reply': 'Reply',
          'forward': 'Forward',
          'new_message': 'New Message',
          'account_name': 'Account Name',
          'trash': 'Trash',
          'compose': 'Compose',
          'settings': 'Settings',
          'accounts': 'Accounts',
          'undo': 'Undo',
          'contact_us': 'Contact Us',
          'terms_and_condition': 'Terms and Condition',
          'valid_required': 'This field is required',
          'valid_email': 'Please enter a valid email',
          'valid_password': 'Please enter a valid password',
          'valid_name': 'Please enter a valid name',
          'valid_phone': 'Please enter a valid phone number',
          'valid_code': 'Please enter a valid code',
          'valid_subject': 'Please enter a valid subject',
          'valid_message': 'Please enter a valid message',
          'msg_draft_saved': 'Draft saved successfully',
          'msg_email_deleted': 'Email deleted successfully',
          'msg_draft_deleted': 'Draft deleted successfully',
          'msg_email_sent': 'Email sent successfully',
          'mark_as_junk': 'Mark as junk',
          'mark_as_unread': 'Mark as unread',
          'archive': 'Archive',
          'toggle_flag': 'Toggle Flag',
          'move_to': 'Move to',
          'move_to_inbox': 'Move to inbox',
          'move_to_sent': 'Move to sent',
          'move_to_spam': 'Move to spam',
          'move_to_trash': 'Move to trash',
          'move_to_draft': 'Move to draft',
          'move_to_starred': 'Move to starred',
          'move_to_archive': 'Move to archive',
          'move_to_junk': 'Move to junk',
          'move_to_flagged': 'Move to flagged',
          'move_to_unread': 'Move to unread',
          'move_to_read': 'Move to read',
          'msg_email_archived': 'Email archived successfully',
          'msg_email_moved': 'Email moved successfully',
          'msg_email_unarchived': 'Email unarchived successfully',
          'msg_email_flagged': 'Email flagged successfully',
          'msg_email_unflagged': 'Email unflagged successfully',
          'msg_email_marked_as_junk': 'Email marked as junk successfully',
          'msg_email_marked_as_unread': 'Email marked as unread successfully',
          'msg_email_marked_as_read': 'Email marked as read successfully',
          'msg_email_starred': 'Email starred successfully',
          'msg_email_unstarred': 'Email unstarred successfully',
          'msg_email_deleted_from': 'Email deleted from',
          'msg_email_moved_to': 'Email moved to',
        },
        'ar': {
          'no_subject': "No Subject",
          'language': 'Language',
          'english': 'English',
          'arabic': 'Arabic',
          'are_you_u_wtd': 'Are you sure to delete?',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'mark_as_read': 'Mark as read',
          'readreceipt': 'Read receipts',
          'security': 'Security',
          'swipe_gestures': 'Swipe Gestures',
          'signature': 'Signature',
          'logout': 'Logout',
          'off': 'Off',
          'on': 'On',
          'set_your_swipe_preferences': 'Set your swipe preferences',
          'set_your_sig': 'Set your signature',
          'starred': 'Starred',
          'search': 'Search',
          'login': 'Login',
          'email': 'Email',
          'inbox': 'Inbox',
          'reset_password': 'Reset Password',
          'attach_file': 'Attach File',
          'from_files': 'From File',
          'from_gallery': 'From File',
          'more_options': 'More Options',
          'save_as_draft': 'Save as Draft',
          'request_read_receipt': 'Request Read Receipt',
          'convert_to_plain_text': 'Convert to plain text',
          'from': 'From',
          'to': 'To',
          'cc': 'CC',
          'edit': 'Edit',
          'bcc': 'Bcc',
          'subject': 'Subject',
          'send': 'Send',
          'reply': 'Reply',
          'forward': 'Forward',
          'new_message': 'New Message',
          'account_name': 'Account Name',
          'trash': 'Trash',
          'compose': 'Compose',
          'settings': 'Settings',
          'accounts': 'Accounts',
          'undo': 'Undo',
          'contact_us': 'Contact Us',
          'terms_and_condition': 'Terms and Condition',
          'valid_required': 'This field is required',
          'valid_email': 'Please enter a valid email',
          'valid_password': 'Please enter a valid password',
          'valid_name': 'Please enter a valid name',
          'valid_phone': 'Please enter a valid phone number',
          'valid_code': 'Please enter a valid code',
          'valid_subject': 'Please enter a valid subject',
          'valid_message': 'Please enter a valid message',
          'msg_draft_saved': 'Draft saved successfully',
          'msg_email_deleted': 'Email deleted successfully',
          'msg_draft_deleted': 'Draft deleted successfully',
          'msg_email_sent': 'Email sent successfully',
          'mark_as_junk': 'Mark as junk',
          'mark_as_unread': 'Mark as unread',
          'archive': 'Archive',
          'toggle_flag': 'Toggle Flag',
          'move_to': 'Move to',
          'move_to_inbox': 'Move to inbox',
          'move_to_sent': 'Move to sent',
          'move_to_spam': 'Move to spam',
          'move_to_trash': 'Move to trash',
          'move_to_draft': 'Move to draft',
          'move_to_starred': 'Move to starred',
          'move_to_archive': 'Move to archive',
          'move_to_junk': 'Move to junk',
          'move_to_flagged': 'Move to flagged',
          'move_to_unread': 'Move to unread',
          'move_to_read': 'Move to read',
          'msg_email_archived': 'Email archived successfully',
          'msg_email_moved': 'Email moved successfully',
          'msg_email_unarchived': 'Email unarchived successfully',
          'msg_email_flagged': 'Email flagged successfully',
          'msg_email_unflagged': 'Email unflagged successfully',
          'msg_email_marked_as_junk': 'Email marked as junk successfully',
          'msg_email_marked_as_unread': 'Email marked as unread successfully',
          'msg_email_marked_as_read': 'Email marked as read successfully',
          'msg_email_starred': 'Email starred successfully',
          'msg_email_unstarred': 'Email unstarred successfully',
          'msg_email_deleted_from': 'Email deleted from',
          'msg_email_moved_to': 'Email moved to',
        },
      };
}
