import 'package:get/get.dart';

class Lang extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
'en': {
          'compose_email': 'Compose',
          'unsaved_changes': 'Unsaved changes',
          'unsaved_changes_message': 'You have unsaved changes. Do you want to save them before leaving?',
          'last_saved': 'Last saved',
          'draft_saved': 'Draft saved',
          'saving_draft': 'Saving draft…',
          'autosaving': 'Autosaving…',
          'add_recipient_error': 'Please add at least one recipient',
          'send_email': 'Send email',
          'email_sent': 'Email sent',
          'error_sending_email': 'Error sending email',
          'save_draft': 'Save draft',
          'scheduling_draft': 'Scheduling draft…',
          'draft_scheduled': 'Draft scheduled',
          'nothing_to_save': 'Nothing to save',
          'nothing_to_schedule': 'Nothing to schedule',
          'draft_loaded': 'Draft loaded',
          'syncing_with_server': 'Syncing with server…',
          'draft_synced': 'Draft synced',
          'sync_failed_retry_later': 'Sync failed. Please try again later.',
          'attachment_large_tap_to_download': 'Large attachment. Tap to download.',
          'hide_cc_bcc': 'Hide CC/BCC',
          'cc_bcc': 'CC/BCC',
          'compose_your_message': 'Your message here...',
          'attach_all': 'Attach all',
          'draft_attachments': '{count} draft attachments',
          'select_date_time': 'Select date & time',
          'date': 'Date',
          'time': 'Time',
          'schedule': 'Schedule',
          'schedule_send': 'Schedule send',
          'schedule_time_past': 'Scheduled time is in the past',
          'work': 'Work',
          'personal': 'Personal',
          'important': 'Important',
          'follow_up': 'Follow up',
          'later': 'Later',
          'custom': 'Custom',
          'custom_category': 'Custom category',
          'select_category': 'Select category',
          'enter_category_name': 'Enter category name',
          'save': 'Save',
          'close': 'Close',
          'low_priority': 'Low priority',
          'high_priority': 'High priority',
          'urgent_priority': 'Urgent priority',
          'normal_priority': 'Normal priority',
          'manage_draft_attachments': 'Draft attachments',
          'reattach_or_view_draft_attachments': 'Re-attach or view draft attachments',
          'know_when_email_is_read': 'Know when your email is read',
          'switch_to_plain_text': 'Switch to plain text',
          'switch_to_rich_text': 'Switch to rich text',
          'add_recipient': 'Add recipient',
          'sending': 'Sending…',
          'discard_draft': 'Discard draft',
          'discard_draft_from_server': 'Discard draft from server',
          'save_current_progress': 'Save your current progress',
          'edit_draft': 'Edit draft',
          'copied_to_clipboard': '{field} copied to clipboard',
          'attach': 'Attach',
          'set_priority': 'Set priority',
          'plain_text': 'Plain text',
          'rich_text': 'Rich text',
          'message_sent': 'Message sent',
          'error_saving_draft': 'Error saving draft',
          'save_error': 'Save error',
          'loading_draft_content': 'Loading draft content…',
          'recover_draft': 'Recover draft',
          'unsaved_draft_found': 'An unsaved draft was found. Would you like to recover it?',
          'recover': 'Recover',
          'just_now': 'just now',
          'minutes_ago': 'minutes ago',
          'hours_ago': 'hours ago',
          'days_ago': 'days ago',
          'view': 'View',
          'reattach': 'Re-attach',
          'no_subject': "No Subject",
          'language': 'Language',
          'english': 'English',
          'arabic': 'Arabic',
          'are_you_u_wtd': 'Are you sure to delete?',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'mark_as_read': 'Mark as read',
          'readreceipt': 'Read receipts',
          'security': 'Security',
          'swipe_gestures': 'Swipe Gestures',
          'signature': 'Signature',
          'logout': 'Logout',
          'off': 'Off',
          'on': 'On',
          'set_your_swipe_preferences': 'Set your swipe preferences',
          'set_your_sig': 'Set your signature',
          'starred': 'Starred',
          'search': 'Search',
          'login': 'Login',
          'email': 'Email',
          'inbox': 'Inbox',
          'drafts': 'Drafts',
          'sent': 'Sent',
          'spam': 'Spam',
          'junk': 'Junk',
          'reset_password': 'Reset Password',
          'password': 'Password',
          'attach_file': 'Attach File',
          'from_files': 'From File',
          'from_gallery': 'From Gallery',
          'more_options': 'More Options',
          'save_as_draft': 'Save as Draft',
          'request_read_receipt': 'Request Read Receipt',
          'convert_to_plain_text': 'Convert to plain text',
          'from': 'From',
          'to': 'To',
          'cc': 'CC',
          'edit': 'Edit',
          'bcc': 'Bcc',
          'subject': 'Subject',
          'send': 'Send',
          'reply': 'Reply',
          'resend': 'Resend',
          'forward': 'Forward',
          'new_message': 'New Message',
          'account_name': 'Account Name',
          'trash': 'Trash',
          'compose': 'Compose',
          'settings': 'Settings',
          'accounts': 'Accounts',
          'undo': 'Undo',
          'error': 'Error',
          'error_in_sending_otp': 'Error in sending OTP',
          'contact_us': 'Contact Us',
          'terms_and_condition': 'Terms and Condition',
          'valid_required': 'This field is required',
          'valid_email': 'Please enter a valid email',
          'valid_password': 'Please enter a valid password',
          'password_must_be_at_least_8_characters':
              'Password must be at least 8 characters',
          'valid_name': 'Please enter a valid name',
          'valid_phone': 'Please enter a valid phone number',
          'valid_code': 'Please enter a valid code',
          'valid_subject': 'Please enter a valid subject',
          'valid_message': 'Please enter a valid message',
          'add_a_recipient': 'Please add a recipient',
          'msg_draft_saved': 'Draft saved successfully',
          'msg_email_deleted': 'Email deleted successfully',
          'msg_draft_deleted': 'Draft deleted successfully',
          'msg_email_sent': 'Email sent successfully',
          'msg_auth_failed': 'Authentication failed',
          'msg_some_thing_went_wrong': 'Something went wrong',
          'msg_enter_and_password': 'Enter OTP & Password',
          'msg_server_error': 'Server error',
          'confirm_save_draft':
              'You have made changes.\nWould you like to save them?',
          'mark_as_junk': 'Mark as junk',
          'mark_as_unread': 'Mark as unread',
          'archive': 'Archive',
          'toggle_flag': 'Toggle Flag',
          'move_to': 'Move to',
          'move_to_inbox': 'Move to inbox',
          'move_to_sent': 'Move to sent',
          'move_to_spam': 'Move to spam',
          'move_to_trash': 'Move to trash',
          'move_to_draft': 'Move to draft',
          'move_to_starred': 'Move to starred',
          'move_to_archive': 'Move to archive',
          'move_to_junk': 'Move to junk',
          'move_to_flagged': 'Move to flagged',
          'move_to_unread': 'Move to unread',
          'move_to_read': 'Move to read',
          'msg_email_archived': 'Email archived successfully',
          'msg_email_moved': 'Email moved successfully',
          'msg_email_unarchived': 'Email unarchived successfully',
          'msg_email_flagged': 'Email flagged successfully',
          'msg_email_unflagged': 'Email unflagged successfully',
          'msg_email_marked_as_junk': 'Email marked as junk successfully',
          'msg_email_marked_as_unread': 'Email marked as unread successfully',
          'msg_email_marked_as_read': 'Email marked as read successfully',
          'msg_email_starred': 'Email starred successfully',
          'msg_email_unstarred': 'Email unstarred successfully',
          'msg_email_deleted_from': 'Email deleted from',
          'msg_email_moved_to': 'Email moved to',
          'msg_otp_sent_to_your_email_and_phone':
              'An one time password sent to your email id and \n phone number \n',
          'msg_otp_sent_successfully': 'OTP sent successfully',
          'msg_sending_otp': 'Sending OTP',
          'msg_password_reset_successfully': 'Password reset successfully',
          'success': 'Success',
          'try_again': 'Try Again',
          'move_message': 'Move Message',
          'enter_search_text': 'Please enter a search term to continue',
          'enter_otp': 'Enter OTP',
          'msg_no_internet': 'No internet connection',
          'resend_otp': 'Resend OTP',
          'continue': 'Continue',
        },
'ar': {
          'compose_email': 'إنشاء رسالة',
          'unsaved_changes': 'تغييرات غير محفوظة',
          'unsaved_changes_message': 'لديك تغييرات غير محفوظة. هل تريد حفظها قبل المغادرة؟',
          'last_saved': 'آخر حفظ',
          'draft_saved': 'تم حفظ المسودة',
          'saving_draft': 'جارٍ حفظ المسودة…',
          'autosaving': 'جارٍ الحفظ التلقائي…',
          'add_recipient_error': 'يرجى إضافة مستلم واحد على الأقل',
          'send_email': 'إرسال البريد',
          'email_sent': 'تم إرسال البريد',
          'error_sending_email': 'حدث خطأ أثناء إرسال البريد',
          'save_draft': 'حفظ المسودة',
          'scheduling_draft': 'جارٍ جدولة المسودة…',
          'draft_scheduled': 'تمت جدولة المسودة',
          'nothing_to_save': 'لا يوجد ما يتم حفظه',
          'nothing_to_schedule': 'لا يوجد ما يتم جدولته',
          'draft_loaded': 'تم تحميل المسودة',
          'syncing_with_server': 'جارٍ المزامنة مع الخادم…',
          'draft_synced': 'تمت مزامنة المسودة',
          'sync_failed_retry_later': 'فشلت المزامنة. يرجى المحاولة لاحقًا.',
          'attachment_large_tap_to_download': 'مرفق كبير. اضغط للتنزيل.',
          'hide_cc_bcc': 'إخفاء ن س/ن مخ',
          'cc_bcc': 'ن س/ن مخ',
          'compose_your_message': 'اكتب رسالتك هنا...',
          'attach_all': 'إرفاق الكل',
          'draft_attachments': '{count} مرفقات مسودة',
          'select_date_time': 'اختر التاريخ والوقت',
          'date': 'التاريخ',
          'time': 'الوقت',
          'schedule': 'جدولة',
          'schedule_send': 'إرسال مجدول',
          'schedule_time_past': 'الوقت المحدد في الماضي',
          'work': 'عمل',
          'personal': 'شخصي',
          'important': 'مهم',
          'follow_up': 'متابعة',
          'later': 'لاحقًا',
          'custom': 'مخصص',
          'custom_category': 'تصنيف مخصص',
          'select_category': 'اختر تصنيفًا',
          'enter_category_name': 'أدخل اسم التصنيف',
          'save': 'حفظ',
          'close': 'إغلاق',
          'low_priority': 'أولوية منخفضة',
          'high_priority': 'أولوية عالية',
          'urgent_priority': 'عاجل',
          'normal_priority': 'عادي',
          'manage_draft_attachments': 'مرفقات المسودة',
          'reattach_or_view_draft_attachments': 'إعادة إرفاق أو عرض مرفقات المسودة',
          'know_when_email_is_read': 'اعرف متى تمت قراءة بريدك',
          'switch_to_plain_text': 'التبديل إلى نص بسيط',
          'switch_to_rich_text': 'التبديل إلى نص منسق',
          'add_recipient': 'إضافة مستلم',
          'sending': 'جارٍ الإرسال…',
          'discard_draft': 'تجاهل المسودة',
          'discard_draft_from_server': 'تجاهل المسودة من الخادم',
          'save_current_progress': 'احفظ تقدمك الحالي',
          'edit_draft': 'تعديل المسودة',
          'copied_to_clipboard': 'تم نسخ {field} إلى الحافظة',
          'attach': 'إرفاق',
          'set_priority': 'تعيين الأولوية',
          'plain_text': 'نص بسيط',
          'rich_text': 'نص منسق',
          'message_sent': 'تم إرسال الرسالة',
          'error_saving_draft': 'حدث خطأ أثناء حفظ المسودة',
          'save_error': 'خطأ في الحفظ',
          'loading_draft_content': 'جارٍ تحميل محتوى المسودة…',
          'recover_draft': 'استعادة المسودة',
          'unsaved_draft_found': 'تم العثور على مسودة غير محفوظة. هل تريد استعادتها؟',
          'recover': 'استعادة',
          'just_now': 'الآن',
          'minutes_ago': 'دقائق مضت',
          'hours_ago': 'ساعات مضت',
          'days_ago': 'أيام مضت',
          'view': 'عرض',
          'reattach': 'إعادة إرفاق',
          'no_subject': "لا يوجد موضوع",
          'language': 'اللغة',
          'english': 'الإنجليزية',
          'arabic': 'العربية',
          'are_you_u_wtd': 'هل أنت متأكد أنك تريد الحذف؟',
          'delete': 'حذف',
          'cancel': 'إلغاء الأمر',
          'mark_as_read': 'تمييز كمقروء',
          'readreceipt': 'إيصالات قراءة',
          'security': 'الأمان',
          'swipe_gestures': 'إيماءات السحب',
          'signature': 'التوقيع',
          'logout': 'تسجيل الخروج',
          'off': 'معطل',
          'on': 'مفعل',
          'set_your_swipe_preferences': 'اضبط تفضيلات السحب لديك',
          'set_your_sig': 'اضبط توقيعك الخاص',
          'starred': 'معلم بنجمة',
          'search': 'البحث',
          'login': 'تسجيل دخول',
          'email': 'البريد الإلكتروني',
          'inbox': 'صندوق الوارد',
          'drafts': 'المسودات',
          'sent': 'الصادر',
          'spam': 'البريد العشوائي',
          'junk': 'الغيز مرغوب فيه',
          'reset_password': 'إعادة تعيين كلمة المرور',
          'password': 'كلمة المرور',
          'attach_file': 'إرفاق ملف',
          'from_files': 'من الملفات',
          'from_gallery': 'من الاستوديو',
          'more_options': 'خيارات أكثر',
          'save_as_draft': 'حفظ كمسودة',
          'request_read_receipt': 'طلب إيصال القراءة',
          'convert_to_plain_text': 'تحويل إلى نص بسيط',
          'from': 'من',
          'to': 'إلى',
          'cc': 'نسخة إلى',
          'edit': 'تحرير',
          'bcc': 'نسخة مخفية إلى',
          'subject': 'الموضوع',
          'send': 'إرسال',
          'reply': 'رد',
          'resend': 'إعادة إرسال',
          'forward': 'إعادة توجيه',
          'new_message': 'رسالة جديدة',
          'account_name': 'اسم الحساب',
          'trash': 'المهملات',
          'compose': 'إنشاء',
          'settings': 'الإعدادات',
          'accounts': 'الحسابات',
          'undo': 'تراجع',
          'error': 'خطأ',
          'error_in_sending_otp': 'خطأ في إرسال كلمة المرور لمرة واحدة',
          'contact_us': 'تواصل معنا',
          'terms_and_condition': 'الشروط والأحكام',
          'valid_required': 'هذا الحقل مطلوب',
          'valid_email': 'يرجى إدخال بريد إلكتروني صحيح',
          'valid_password': 'يرجى إدخال كلمة مرور صحيحة',
          'password_must_be_at_least_6_characters':
              'يجب أن تكون كلمة المرور على الأقل 6 أحرف',
          'valid_name': 'يرجى إدخال اسم صحيح',
          'valid_phone': 'يرجى إدخال رقم هاتف صحيح',
          'valid_code': 'يرجى إدخال رمز صحيح',
          'valid_subject': 'يرجى إدخال موضوع صحيح',
          'valid_message': 'يرجى إدخال رسالة صحيحة',
          'msg_draft_saved': 'تم حفظ المسودة بنجاح',
          'msg_email_deleted': 'تم حذف البريد الإلكتروني بنجاح',
          'msg_draft_deleted': 'تم حذف المسودة بنجاح',
          'msg_email_sent': 'تم إرسال البريد الإلكتروني بنجاح',
          'msg_auth_failed': 'فشل التوثيق',
          'msg_some_thing_went_wrong': 'حدث خطأ ما',
          'msg_enter_and_password': 'أدخل كلمة المرور لمرة واحدة وكلمة المرور',
          'msg_server_error': 'خطأ في الخادم',
          'confirm_save_draft': 'لقد قمت بإجراء تغييرات.\nهل ترغب في حفظها؟',
          'mark_as_junk': 'تمييز كبريد غير هام',
          'mark_as_unread': 'تمييز كغير مقروء',
          'archive': 'أرشفة',
          'toggle_flag': 'تغيير تمييز',
          'move_to': 'نقل إلى',
          'move_to_inbox': 'نقل إلى صندوق الوارد',
          'move_to_sent': 'نقل إلى الصادر',
          'move_to_spam': 'نقل إلى البريد العشوائي',
          'move_to_trash': 'نقل إلى المهملات',
          'move_to_draft': 'نقل إلى المسودات',
          'move_to_starred': 'نقل إلى المعلم بنجمة',
          'move_to_archive': 'نقل إلى الأرشيف',
          'move_to_junk': 'نقل إلى الغيز مرغوب فيه',
          'move_to_flagged': 'نقل إلى المعلم',
          'move_to_unread': 'نقل إلى غير مقروء',
          'move_to_read': 'نقل إلى مقروء',
          'msg_email_archived': 'تم أرشفة البريد الإلكتروني بنجاح',
          'msg_email_moved': 'تم نقل البريد الإلكتروني بنجاح',
          'msg_email_unarchived': 'تم إلغاء أرشفة البريد الإلكتروني بنجاح',
          'msg_email_flagged': 'تم تمييز البريد الإلكتروني بنجاح',
          'msg_email_unflagged': 'تم إلغاء تمييز البريد الإلكتروني بنجاح',
          'msg_email_marked_as_junk':
              'تم تمييز البريد الإلكتروني كغير هام بنجاح',
          'msg_email_marked_as_unread':
              'تم تمييز البريد الإلكتروني كغير مقروء بنجاح',
          'msg_email_marked_as_read': 'تم تمييز البريد الإلكتروني كمقروء بنجاح',
          'msg_email_starred': 'تم تمييز البريد الإلكتروني بنجاح',
          'msg_email_unstarred': 'تم إلغاء تمييز البريد الإلكتروني بنجاح',
          'msg_email_deleted_from': 'تم حذف البريد الإلكتروني من',
          'msg_email_moved_to': 'تم نقل البريد الإلكتروني إلى',
          'msg_otp_sent_to_your_email_and_phone':
              'تم إرسال كلمة المرور لمرة واحدة إلى بريدك الإلكتروني و\n رقم هاتفك\n',
          'msg_otp_sent_successfully': 'تم إرسال كلمة المرور لمرة واحدة بنجاح',
          'msg_sending_otp': 'إرسال كلمة المرور لمرة واحدة',
          'msg_password_reset_successfully': 'تم إعادة تعيين كلمة المرور بنجاح',
          'success': 'نجاح',
          'try_again': 'حاول مرة أخرى',
          'move_message': 'Move Message',
          'enter_search_text': 'يرجى إدخال مصطلح بحث للمتابعة',
          'msg_no_internet': 'لا يوجد اتصال بالإنترنت',
          'resend_otp': 'إعادة إرسال رمز التحقق',
          'continue': 'متابعة',
        }
      };
}
