import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: false,
)
Future<void> configureDependencies({String env = Environment.dev}) async {
  // init() is generated by injectable and is synchronous; keeping this method async allows callers to `await` it safely.
  init(getIt, environment: env);
}
